from datetime import datetime
from pathlib import Path


def generate_report(alert_text, analysis):

    current_time = datetime.now()

    report = f"""# 🛡️ AI SOC INCIDENT REPORT

**Incident ID:** IR-{current_time.strftime("%Y%m%d-%H%M%S")}

**Generated:** {current_time.strftime("%d %B %Y, %I:%M:%S %p")}

**Classification:** Internal

**Severity:** HIGH

---

# 📋 Alert Details

{alert_text}

---

# 🤖 AI SOC Analysis

{analysis}

---

# 📌 Report Information

- Generated by: **AI SOC Assistant**
- Report Format: Markdown (.md)
- Analysis Engine: OpenRouter LLM
"""

    return report


def save_report(report):

    reports_folder = Path("reports")

    reports_folder.mkdir(exist_ok=True)

    filename = f"Incident_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    filepath = reports_folder / filename

    with open(filepath, "w", encoding="utf-8") as file:
        file.write(report)

    return filepath