from datetime import datetime
from pathlib import Path


def generate_report(alert_text, analysis):

    report = f"""# Incident Report

## Generated

{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

# Alert Information

{alert_text}

---

# AI SOC Analysis

{analysis}

---

Generated by

**AI SOC Assistant**
"""

    return report


def save_report(report):

    reports_folder = Path("reports")

    reports_folder.mkdir(exist_ok=True)

    filename = f"Incident_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    filepath = reports_folder / filename

    with open(filepath, "w", encoding="utf-8") as file:

        file.write(report)

    return filepath