from datetime import datetime
from pathlib import Path


# ============================================================
# REPORT GENERATION
# ============================================================

def generate_report(
    context,
    analysis,
    risk_assessment=None
):
    """
    Generate the final SOC incident report.

    The deterministic risk engine remains the source
    of truth for severity.
    """

    current_time = datetime.now()

    if not isinstance(
        risk_assessment,
        dict
    ):
        risk_assessment = {}

    severity = risk_assessment.get(
        "level",
        "UNKNOWN"
    )

    risk_score = risk_assessment.get(
        "score",
        "UNKNOWN"
    )

    incident_status = risk_assessment.get(
        "status",
        "UNKNOWN"
    )

    confidence = risk_assessment.get(
        "confidence",
        "UNKNOWN"
    )

    # ========================================================
    # INCIDENT ID
    # ========================================================

    incident_id = (
        f"IR-"
        f"{current_time.strftime('%Y%m%d-%H%M%S')}"
    )

    # ========================================================
    # REPORT
    # ========================================================

    report = f"""# 🛡️ AI SOC INCIDENT REPORT

**Incident ID:** {incident_id}

**Generated:** {current_time.strftime("%d %B %Y, %I:%M:%S %p")}

**Severity:** {severity}

**Risk Score:** {risk_score}/100

**Incident Status:** {incident_status}

**Confidence:** {confidence}

---

# 📋 Incident Context

{context}

---

# 🤖 AI SOC Analysis

{analysis}

---

# 📌 Report Information

- Generated by: **AI SOC Assistant**
- Report Format: **Markdown (.md)**
- Analysis Engine: **OpenRouter LLM**
- Severity Source: **Deterministic Risk Engine**

---

# ⚠️ Evidence Disclaimer

The AI analysis is based only on the evidence supplied
in the incident context.

A risk score or MITRE ATT&CK classification does not
by itself confirm successful compromise.

Where evidence is insufficient, further SOC investigation
is required.
"""

    return report


# ============================================================
# REPORT STORAGE
# ============================================================

def save_report(report):
    """
    Save the generated SOC incident report
    inside the reports directory.

    Returns:
        Path: Path to the saved Markdown report.
    """

    reports_folder = Path("reports")

    reports_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        f"Incident_Report_{timestamp}.md"
    )

    filepath = reports_folder / filename

    filepath.write_text(
        report,
        encoding="utf-8"
    )

    return filepath